// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpaYWw8YOLg41GZBXPPE51AShTSF9dJeI',
    appId: '1:613281152231:web:eee456975b61efe1d2f642',
    messagingSenderId: '613281152231',
    projectId: 'fruits-market-a0791',
    authDomain: 'fruits-market-a0791.firebaseapp.com',
    storageBucket: 'fruits-market-a0791.firebasestorage.app',
    measurementId: 'G-HJS097EPK2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWeNaO3zzCQzSLzIy339XkHwIzZPaKuts',
    appId: '1:613281152231:android:7d642ed38fa81302d2f642',
    messagingSenderId: '613281152231',
    projectId: 'fruits-market-a0791',
    storageBucket: 'fruits-market-a0791.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCf_txJhS3--VdCfdLonXN5tNKnSF93BGw',
    appId: '1:613281152231:ios:5caaad381a716215d2f642',
    messagingSenderId: '613281152231',
    projectId: 'fruits-market-a0791',
    storageBucket: 'fruits-market-a0791.firebasestorage.app',
    iosBundleId: 'com.example.fruitsMarket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCf_txJhS3--VdCfdLonXN5tNKnSF93BGw',
    appId: '1:613281152231:ios:5caaad381a716215d2f642',
    messagingSenderId: '613281152231',
    projectId: 'fruits-market-a0791',
    storageBucket: 'fruits-market-a0791.firebasestorage.app',
    iosBundleId: 'com.example.fruitsMarket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpaYWw8YOLg41GZBXPPE51AShTSF9dJeI',
    appId: '1:613281152231:web:772d8094ac15b9acd2f642',
    messagingSenderId: '613281152231',
    projectId: 'fruits-market-a0791',
    authDomain: 'fruits-market-a0791.firebaseapp.com',
    storageBucket: 'fruits-market-a0791.firebasestorage.app',
    measurementId: 'G-VBHC5HPVRH',
  );
}
